export {default as RootLayout} from './RootLayout'
export {default as Home} from './Home'
export {default as Courses} from './Courses'
export {default as Details} from './Details'
export {default as AuthPage} from './AuthPage'
export {default as ContactUs} from './ContactUs'
